FILENAME_BINEXP_HEADER = "binexp.h"
FILENAME_DEFINES_HEADER = "defines.h"
FILENAME_NOISY = "noisy.exe"

TEMPLATE_CHAR_ARRAY = "unsigned char BINARY_ARRAY[] = {{ {} }};"
TEMPLATE_DEFINE = "#define {}\n"

TEMPLATE_PRINT_NOISE_TEXT = '_PRINT_NOISE_TEXT "{}"'
TEMPLATE_DNS_NOISE_ARG = '_DNS_NOISE_ARG "{}"'

PRINT_NOISE_ENABLED = "_PRINT_NOISE_ENABLED"
DNS_NOISE_ENABLED = "_DNS_NOISE_ENABLED"
